// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsnnzrbxupmhtgutajwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdzbm56cmJ4dXBtaHRndXRhandxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTc0MDMsImV4cCI6MjA2MDYzMzQwM30.eW5ZnpauytqrEuVkSuCoO_82_CE0586Cz7nrfRb4uIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);